### ISSUE TITLE
handle crash on homepage

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/gow#1]
client is "expecting" JSON data, but when it's empty, client will crash the app. The interesting part is this code:

```reason
React.useEffect0(() => {
    Js.Promise.(
      fetch("/api/url/list")
      |> then_(response => response##json())
      |> then_(responseJSON => {
           setState(_previousState => URLs(responseJSON));
           Js.Promise.resolve();
         })
      |> catch(_err => {
           setState(_previousState => ErrorFetch);
           Js.Promise.resolve();
         })
      |> ignore
    );

    None;
  });
}
```

On `stats` fragments, I trick that by rejecting the promise using 204 status code:

```go
func GetHitsStatsBySlug(db *sql.DB, w http.ResponseWriter, r *http.Request) {
	params := r.URL.Query()
	slug := params.Get(":slug")
	payload := models.GetHitsBySlug(db, slug)

	if payload == nil {
		emptyData := make([]string, 0)

		// FIXME: this is temporary fix to our frontend!
		ResponseJSON(w, http.StatusNoContent, notFound{emptyData})

		return
	}

	ResponseJSON(w, http.StatusOK, payload)
}
```

Absolutely this is not a good solution, I need to know how to handle "unexpected" response in Reason, so if the payload I need is like this:

```json
{
  "data": [{ "id": 124, "url": "https://evlfctry.pro/send-nudes" }]
}
```

But the given response is like this:

```json
{
  "data": null
}
```

How to handle that beautifully in Reason so the client will not crash?

**Comment by r17x** [comment]
I think, we don't need to `interop` fetch. 

some random guy in the internet was publish `a nice reason article` : here we go https://medium.com/@kevanstannard/how-to-fetch-json-data-with-reasonml-a4507ec945ad 

1. Fetch is (side effect) | bs-fetch
2. Result of side effect need handle too | bs-json (encode/decode/typing)

Good job :+1:

**Comment by faultables** [comment]
Thank you, will read the article!

**Comment by r17x** [comment]
I take this issue, `WIP`.
