### ISSUE TITLE
assets is not found

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/gow#14]
Currently just updated the gow docker image to `latest` tag but unfortunately there is critical error that assets are not found, and I think this bug exists after [we migrated](https://github.com/evilfactorylabs/gow/commit/06424091feebe93eeedcb21573bf2f7976ed4c17) to react-scripts

Overall for core functionality was worked as expected, I just rolled back the deployment to gow:0.3.0 and now everything is work seamlessly

/cc @ri7nz

**Comment by r17x** [comment]
Tomorrow, I will check it.

**Comment by faultables** [comment]
Santaaai, take your time pack

**Comment by r17x** [comment]
@faultable  https://github.com/evilfactorylabs/gow/pull/15 di PR tersebut masih belum kelar masalah serve `directory` web supaya semua yang diminta `index.html` di serve oleh `backend` (golang).

**Comment by faultables** [comment]
gw coba handle di sisi Go nya, tp gak bisa janjiin kapan kelarnya

/remind me in next week

**Comment by faultables** [comment]
Udah gw fix ya @ri7nz mohon di cek lg, sorry kalau gw slowres

Fix nya basically gw cuma list semua assets yang ada di web/build, terus gw mount itu as static serve HAHAHA
