### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/gow#18]
Aslinya ini bukan kesalahan pengetikan sih tapi lebih ke kesalahan penulisan (gw yakin itu BEDA), jadi harusnya teh yang dari [bagian ini](https://github.com/evilfactorylabs/gow#development), bukan `GOW_TOKEN=` tapi `TOKEN` aja yang walaupun belum berguna (itu env variable) tapi bikin aplikasi tersebut ga berjalan kalau belum terdefinisi dan juga bila tidak ada nilainya

Kemungkinan solusi dalam satu baris: 

- via vim: `%s/GOW_TOKEN/TOKEN/g`
- via sed: `sed -i 's/\bGOW_TOKEN/TOKEN/g' README.md`

**Comment by nikita812** [comment]
i can do this in english

**Comment by r17x** [comment]
https://github.com/evilfactorylabs/gow/pull/19
