### ISSUE TITLE
auth bypass UX

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/gow#2]
## Ikhtisar

Jika kamu mengakses https://evlfctry.pro, kamu akan diberikan dialog otentikasi untuk _username_ dan _password_ (HTTP Basic) dan jika kamu memilih Cancel (atau menekan `esc` di papan ketik), dialog tersebut akan hilang, dan bagaimanapun kamu dapat mengakses fragment "new" alias `/#/new` yang berguna untuk membuat data baru

Bagaimanapun kamu tidak dapat menyimpan data tersebut—karena kamu belum terotentikasi, dan peladen akan memberikan kode status 401—namun ketika kamu masih bandel untuk mencoba menyimpannya, dialog otentikasi akan muncul kembali dan bila memilih Cancel, aplikasi menampilkan "succesfully saved!" yang mana itu adalah sebuah kebohongan dan bohong itu dosa ya sobat open source

## Saran

Jika respon dari peladen bukan 20x, maka tampilkan pesan galat seperti "Successfully failed to save" yang intinya setidaknya jangan berbohong lah

**Comment by zakybilfagih** [comment]
Saya akan coba memperbaiki isu ini!

**Comment by faultables** [comment]
Great, terima kasih!

Jika ada kendala dalam *bootstrap project* ini di *development*, let us know :))
